### ISSUE TITLE
Don't validate return values in exit methods using the `example` in the specification by default

### ISSUE THREAD

**Issue by fabdrol** [node-machine/machinepack#5]
I ran into an issue using https://github.com/mikermcneil/machinepack-mandrill. That machinepack retrieves data from the Mandrill API. For me, this worked exactly once (when there were no templates), after that the validation failed as the result was validated against the example in the definition. It took me hours to track down the issue.

To me, this behaviour is counter-intuitive. Testing the type of the top-level object makes sense to me (although using the example as the source of the validation doesn't, maybe add a separate key for that?) but testing the content of (each?) entire document does not make sense: for large arrays it'll be slow and - especially with external APIs - the response data cannot always be guaranteed (or changes often).

**Comment by sgress454** [comment]
Hi @fabdrol, thanks for posting.  There is indeed an issue with that machine, but it's not a systemic issue in machinepack itself.  It's not the case that the machine is validating the return value against the example--in fact, the machine runtime will always _coerce_ the return value to match the schema in the example.  The issue in this case is that the example _is itself invalid_.  Specifically, the `null` value used in several keys (e.g. `publish_text`) is not valid in an exit example.  It may be the case that this was allowed in earlier versions of the machine runtime, and that this particular machine was not updated properly (this is what tests are for...).

**Comment by fabdrol** [comment]
@sgress454 thanks for explaining, very thorough answer. I'll send in some PRs to fix the machine. It seems that the tests were there once, but have been deleted.
